config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#index"
  get 'my_courses', to: 'courses#my_courses'
  resources :courses, :stations, :questions, :station_categories, :payments
  resources :user_courses, only: [:create]
  authenticate :user do
    resources :courses, :except => [:show, :index]
    resources :stations, :questions, :station_categories
  end
  mount StripeEvent::Engine, at: '/stripe-event'
  resources :stations do
    put :complete, on: :member
  end
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :course
  belongs_to :station_category
  has_many :questions, dependent: :destroy
  has_many :station_categories
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :scenario, presence: true
  validates :course_id, presence: true
  validates :station_category_id, presence: true

  has_many :favorite_stations # just the 'relationships'
  has_many :completed_by_users, through: :favourite_stations, source: :user # the actual users favoriting a recip
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:edit, :update, :show, :destroy, :complete]
  before_action :check_user_has_station, only: [:show]
  attr_accessor :course_id,
  
  def index
    @stations = Station.all
  end

  def new
    @station = Station.new
    course = Course.find_by_id(params[:course_id]) if params[:course_id]
    if params[:course_id] && !course.station_categories.any?
      flash[:danger] = "#{course.title} doesn't have any station categories, create one:"
      redirect_to new_station_category_path
    end
  end

  def show
    @questions = @station.questions if @station.questions.any?
    stations = Array.new(@station.station_category.stations)
    current_position_id = stations.find_index(@station)
    @next_station = stations[current_position_id + 1] if stations[current_position_id + 1]
  end

  def create
    @station = Station.new(station_params)
    course = Course.find_by_id(station_params[:course_id])
    if @station.save
      flash[:success] = "Station created!"
      redirect_to course_path(@station.course)
    else
      @course = course
      render 'new'
    end
  end

  def update
    if @station.update(station_params)
      flash[:success] = "Station was successfully updated."
      redirect_to station_path(@station)
    else
      render "edit"
    end
  end

  def destroy
    if @station.destroy
      flash[:success] = "Station has been deleted"
      redirect_to course_path(@station.course)
    else
      flash[:danger] = "Problem deleting station"
      redirect_to course_path(@station.course)
    end
  end

  def complete
    type = params[:type]
    if type == "1"
      @completed = "Completed"
      current_user.completed_stations << @station
      respond_to do |format|
        format.js
      end
    elsif type == "0"
      current_user.completed_stations.delete(@station)
      @completed = "Incomplete"
      respond_to do |format|
        format.js
      end
    else
      render js: "alert('error');"
    end
  end


  private
  def station_params
    params.require(:station).permit(:title, :description, :scenario, :course_id, :station_category_id)
  end

  def set_station
    @station = Station.find(params[:id])
  end

  def check_user_has_station
    parent_course = @station.course.id if @station.course
    if !user_signed_in? || current_user.courses.find_by_id(parent_course).nil?
      flash[:danger] = "You are not subscribed to a course with this station"
      redirect_to courses_path
    end
  end

end

app/helpers/stations_helper.rb
module StationsHelper
  def selected(params)
    if !params[:station_category_id].nil?
      return params[:station_category_id]
    else
      return nil
    end
  end

  def check_course_id(params)
    if params[:course_id]
      @course = Course.find_by_id(params[:course_id])
      @station_categories = @course.station_categories.all
      return @course, @station_categories
    elsif @course
      @station_categories = @course.station_categories.all
      return @station_categories
    else
      @station_categories = StationCategory.all
      return @station_categories
    end
  end

end

app/views/stations/_example.html.erb
<div class="card">
    <div class="card-header" id="heading1">
        <h2 class="mb-0">
            <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#collapse1">
              First example question: what are the boundaries of the femoral triangle? <underline><strong>Show answer</strong></underline>
            </button>
        </h2>
    </div>
    <div id="collapse1" class="collapse" aria-labelledby="heading1" data-parent="#scenario-accordion">
        <div class="card-body">
            <p>Quisque nec elit vestibulum, blandit felis a, vehicula erat. Nunc nec tellus sit amet lacus gravida hendrerit ac a ipsum. Integer hendrerit vehicula tortor eget rhoncus. Proin et ipsum in arcu ultrices facilisis sed non elit. Sed a vulputate enim, ut tempor turpis. Ut vehicula nisl vitae lacus scelerisque hendrerit. Vivamus non molestie enim, eu rhoncus turpis.</p>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-header" id="heading2">
        <h2 class="mb-0">
            <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#collapse2">
              Second example question: how would you approach this scenario? <underline><strong>Show answer</strong></underline>
            </button>
        </h2>
    </div>
    <div id="collapse2" class="collapse" aria-labelledby="heading2" data-parent="#scenario-accordion">
        <div class="card-body">
            <p>Quisque nec elit vestibulum, blandit felis a, vehicula erat. Nunc nec tellus sit amet lacus gravida hendrerit ac a ipsum. Integer hendrerit vehicula tortor eget rhoncus. Proin et ipsum in arcu ultrices facilisis sed non elit. Sed a vulputate enim, ut tempor turpis. Ut vehicula nisl vitae lacus scelerisque hendrerit. Vivamus non molestie enim, eu rhoncus turpis.</p>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-header" id="heading3">
        <h2 class="mb-0">
            <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#collapse3">
              Third example question: who would you escalate this problem to? <underline><strong>Show answer</strong></underline>
            </button>
        </h2>
    </div>
    <div id="collapse3" class="collapse" aria-labelledby="heading3" data-parent="#scenario-accordion">
        <div class="card-body">
            <p>Quisque nec elit vestibulum, blandit felis a, vehicula erat. Nunc nec tellus sit amet lacus gravida hendrerit ac a ipsum. Integer hendrerit vehicula tortor eget rhoncus. Proin et ipsum in arcu ultrices facilisis sed non elit. Sed a vulputate enim, ut tempor turpis. Ut vehicula nisl vitae lacus scelerisque hendrerit. Vivamus non molestie enim, eu rhoncus turpis.</p>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-header" id="heading4">
        <h2 class="mb-0">
            <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#collapse4">
              Fourth example question: how would you manage this patient with traumatic head injury? <underline><strong>Show answer</strong></underline>
            </button>
        </h2>
    </div>
    <div id="collapse4" class="collapse" aria-labelledby="heading4" data-parent="#scenario-accordion">
        <div class="card-body">
            <p>Quisque nec elit vestibulum, blandit felis a, vehicula erat. Nunc nec tellus sit amet lacus gravida hendrerit ac a ipsum. Integer hendrerit vehicula tortor eget rhoncus. Proin et ipsum in arcu ultrices facilisis sed non elit. Sed a vulputate enim, ut tempor turpis. Ut vehicula nisl vitae lacus scelerisque hendrerit. Vivamus non molestie enim, eu rhoncus turpis.</p>
        </div>
    </div>
</div>

app/views/stations/_form.html.erb
<div class="row">
  <div class="col-sm-12">
    <%= form_for(@station, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <% check_course_id(params) %>

    <div class="form-group">
      <div class='row'>
        <div class="control-label col-2">
          <%= f.label :title %>
        </div>
        <div class="col-10">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of station", autofocus: true  %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class='row'>
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class='col-sm-10'>
          <%= f.text_area :description, rows: 5, class: "form-control", placeholder: "Station Description" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class='row'>
        <div class="control-label col-sm-2">
          <%= f.label :scenario %>
        </div>
        <div class='col-sm-10'>
          <%= f.text_area :scenario, rows: 5, class: "form-control", placeholder: "Station Scenario" %>
        </div>
      </div>
    </div>

    <% if @course %>
      <%= f.hidden_field :course_id, :value => "#{@course.id}" %>
      <p><%= "<strong>Course: #{@course.title}</strong>".html_safe %></p>
    <% else %>
      <div class='form-group'>
        <div class="row">
          <div class="col-sm-12">
            <strong>Course: </strong><%= f.collection_select(:course_id, Course.all, :id, :title, {}, {:class=>'form-control'}) %>
          </div>
        </div>
      </div>
    <% end %>

    <div class='form-group'>
      <div class="row">
        <div class="col-sm-12">
          <strong>Category: </strong>
            <%= f.collection_select(:station_category_id, @station_categories, :id, :name, { :class=>'form-control' }) if params[:action] == "edit" %>
            <%= f.collection_select(:station_category_id, @station_categories, :id, :name, { :class=>'form-control', :selected=>selected(params) }) if params[:action] != "edit"%>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class='row'>
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<%= params %>

app/views/stations/complete.js.erb
//$('.label<%=@station.id %>').html('<%= j @completed %>');

app/views/stations/edit.html.erb
<%= render 'shared/errors', obj: @station %>

<%= render 'form' %>

app/views/stations/index.html.erb
  <div class='row'>
    <div clas='col-md-12'>
      <h2>Station index</h2>
      <ul class="list-group">
        <% @stations.each do |station| %>
        <li class="list-group-item"><%= station.title %></li>
        <% end %>
      </ul>
    </div>
  </div>

app/views/stations/new.html.erb
<%= render 'shared/errors', obj: @station %>

<div class="row">
  <div class="col-sm-12">
    <%= form_for(@station, :html => {class: "form-horizontal", role: "form"}) do |f| %>

    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :title %>
      </div>
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control", placeholder: "Title of station", autofocus: true  %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :description %>
      </div>
      <div class='col-sm-10'>
        <%= f.text_area :description, rows: 5, class: "form-control", placeholder: "Station Description" %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :scenario %>
      </div>
      <div class='col-sm-10'>
        <%= f.text_area :scenario, rows: 5, class: "form-control", placeholder: "Station Scenario" %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.collection_select(:course_id, Course.all, :id, :title) %>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/stations/show.html.erb
<div class='header-row'>
  <div class='container'>
    <div class='row'>
      <div class='col-lg-12 breadcrumbs'>
        <h4><%= link_to "Back to #{@station.course.title}", course_path(@station.course) %>
          <% if @next_station %>
             |
             <%= link_to"Next station", station_path(@next_station) %>
          <% end %>
        </h4>
      </div>
    </div>
  </div>
</div>
<div class="container station-show">
  <div class='row'>
    <div class='col-lg-8 offset-lg-2 text-right mark-complete' style='margin-top: 30px;'>
      Mark as complete:
      <span class='float-right pl-2'>
        <%= form_with(url: complete_station_path(@station), method: 'put', id: "complete_toggle_#{@station.id}") do |f| %>
          <%  if current_user.completed_stations.find_by_id(@station).present?
                @checked = true
              else
                @checked = false
              end
          %>
          <%= f.label :type, :class => "label label#{@station.id}", :for => "customSwitch#{@station.id}" do %>
            <%= f.check_box(:type, :class => "label__checkbox", :id => "customSwitch#{@station.id}", :onclick =>"Rails.fire(form, 'submit');", :checked => @checked ) %>
            <span class="label__text">
              <span class='label__check'>
                <i class="fa fa-check icon"></i>
              </span>
            </span>
          <% end %>
        <% end %>
      </span>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <div class="accordion" id="scenario-accordion">
        <div class='card' id="scenario-card">
          <div class="card-header">
            <%= @station.title %>
          </div>
          <div class="card-body"><%= raw @station.scenario %></div>
        </div>
        <% @station.questions.each do |question| %>
          <!-- Start collapse group -->
            <div class="card">
                <div class="card-header" id="heading<%= "#{question.id}".html_safe %>">
                  <button type="button" class="btn btn-link dropdown-toggle" data-toggle="collapse" data-target="#collapse<%= "#{question.id}".html_safe %>">
                    <%= question.title %>
                  </button>
                  <%= link_to_if(current_user.admin?, 'Edit', edit_question_path(question), class: "btn btn-sm btn-link float-right"){} %>
                  <%= link_to_if(current_user.admin?, 'Delete', question_path(question), method: :delete, class: "btn btn-sm btn-link float-right" ){} %>
                </div>
                <div id="collapse<%= "#{question.id}".html_safe %>" class="collapse" aria-labelledby="heading<%= "#{question.id}".html_safe %>" data-parent="#scenario-accordion">
                    <div class="card-body">
                        <p><%= question.answer %></p>
                    </div>
                </div>
            </div>
          <!-- End collapse group -->
        <% end %>
        <%= link_to_if(current_user.admin?, 'Create Q for this station', new_question_path(:station_id => @station.id), class: "btn btn-outline-primary mt-3" ){} %>
      </div>
    </div>
  </div>
</div>