config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#index"
  get 'my_courses', to: 'courses#my_courses'
  resources :courses, :stations, :questions, :station_categories, :payments
  resources :user_courses, only: [:create]
  authenticate :user do
    resources :courses, :except => [:show, :index]
    resources :stations, :questions, :station_categories
  end
  mount StripeEvent::Engine, at: '/stripe-event'
  resources :stations do
    put :complete, on: :member
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :require_admin, only: [:create, :update, :destroy]
  before_action :set_course, only: [:edit, :update, :show, :destroy]

  def my_courses
    if user_signed_in? && current_user.courses.any? && !current_user.admin
      @courses = current_user.courses.all
    elsif user_signed_in? && current_user.admin
      @courses = Course.all
    else
      flash[:danger] = "You have no courses!"
      redirect_to courses_path
    end
  end

  def new
    @course = Course.new
  end

  def index
    @courses = Course.all
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:success] = "Course has been successfully created"
      redirect_to course_path(@course)
    else
      render 'new'
    end
  end

  def update
    if @course.update(course_params)
      flash[:success] = "Course was successfully updated."
      redirect_to course_path(@course)
    else
      render "edit"
    end
  end

  def show
    @course_stations = @course.stations.all if @course.stations
  end

  def destroy
    if @course.destroy
      flash[:success] = "Course has been deleted"
      redirect_to courses_path
    else
      flash[:danger] = "Problem deleting course"
      redirect_to courses_path
    end
  end

  private
  def require_admin
    if !current_user.admin?
      flash[:danger] = "You need to be an admin to do that"
      redirect_to courses_path
    end
  end
  def course_params
    params.require(:course).permit(:title, :description, :category, :price)
  end
  def set_course
    @course = Course.find(params[:id])
  end
end

app/views/courses/_admin_panel.html.erb
<div class='text-right'>
  <%= link_to 'Create a category for this course', new_station_category_path(:course_id => @course.id), class: "btn btn-outline-primary mb-3" %>
  <button type="button" class="btn btn-outline-primary dropdown-toggle mb-3" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Create station for..<span class="caret"></span>
  </button>
  <div class="dropdown-menu" role="menu" aria-labelledby="dropdownMenuButton">
    <% @course.station_categories.each do |sc| %>
    <%= link_to sc.name, new_station_path(:course_id => @course.id, :station_category_id => sc.id), class: "dropdown-item" %>
    <% end %>
  </div>
</div>

app/views/courses/_all_course_stations.html.erb
<% if user_signed_in? && current_user.courses.find_by_id(@course.id) %>
<h2><%= @course.title %></h2>
  <% if @course.stations.any? %>
    <ul class="list-group">
      <% @course.stations.each do |station| %>
      <li class="list-group-item">
        <%= link_to station.title, station_path(station) %>
        <span class="float-right button-group">
          <%= link_to_if(current_user.admin?, 'Edit', edit_station_path(station), class: "btn btn-sm btn-primary"){} %>
          <%= link_to_if(current_user.admin?, 'Delete', station_path(station), method: :delete, class: "btn btn-sm btn-danger" ){} %>
        </span>
      </li>
      <% end %>
    </ul>
  <% end %>

app/views/courses/_course_card.html.erb
<div class="card course-card mt-4">
  <%= link_to course_path(obj) do %>
    <div class="card-header">
      <h2><%= obj.title %></h2>
    </div>
    <div class="card-body">
      <p class="card-text">
        <%= obj.description %>
      </p>
    </div>
    <div class='card-footer text-right'>
      <% if user_signed_in? && current_user.courses.find_by_id(obj.id) %>
        <%= link_to "Subscribed", course_path(obj), class: "btn btn-primary" %>
      <% else %>
        <%= link_to "Find out more", course_path(obj), class:"btn btn-outline-primary" %>
      <% end %>
      <% if user_signed_in? && current_user.admin? %>
      <div style='border-top: 1px solid #EEE;' class='mt-3'>
        <%= link_to 'Edit', edit_course_path(obj), class: "btn btn-sm btn-link" %>
        <%= link_to 'Delete', course_path(obj), method: :delete, class: "btn btn-sm btn-link" %>
      </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/courses/_course_description_and_signup.html.erb
<div class="row">
  <div class="col-sm-12">
    <ul class="list-group">
      <li class="list-group-item"><%= @course.description %></li>
      <li class="list-group-item"><strong>Price:</strong> <%= "£" + "#{@course.price}" %></li>
    </ul>
  </div>
</div>
<div class='row mt-3'>
  <div class='col-sm-12'>
    <% if user_signed_in? %>
      <%= link_to "Sign up for this course", payments_path(course: @course), :method => :post, class: "btn btn-lg btn-primary sign-up-button", remote: true %>
    <% else %>
      <%= link_to t(".sign_up"), new_user_registration_path %>
    <% end %>
  </div>
</div>
<script src="https://js.stripe.com/v3/"></script>

app/views/courses/_form.html.erb
<div class="row">
  <% if user_signed_in? && current_user.admin? %>
  <div class='col-sm-4'>
    <h3>Users signed up to this course:</h3><br />
    <ul>
    <% if @course.users.any? %>
      <ul>
      <% @course.users.each do |user| %>
        <li><%= user.email %></li>
      <% end %>
      </ul>
    <% else %>
      <p>No users are signed up yet...</p>
    <% end %>
  </div>
  <% end %>
  <div class="col-sm-8">
    <%= form_for(@course, :html => {class: "form-horizontal", role: "form"}) do |f| %>

    <div class="form-group">
      <div class='row'>
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-10">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of course", autofocus: true  %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class='row'>
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class='col-sm-10'>
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Course Description" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class='row'>
        <div class="control-label col-sm-2">
          <%= f.label :category %>
        </div>
        <div class='col-sm-10'>
          <%= f.text_field :category, rows: 10, class: "form-control", placeholder: "Course Category" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class='row'>
        <div class="control-label col-sm-2">
          <%= f.label :price %>
        </div>
        <div class='col-sm-10'>
          <%= f.text_field :price, class: "form-control", placeholder: "Price" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class='row'>
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/courses/edit.html.erb
<%= render 'shared/errors', obj: @course %>

<%= render 'form' %>

app/views/courses/index.html.erb
<div class='container'>
  <div class='row pt-1'>
    <div class='col-md-12'>
      <% i = 1 %>
      <% @courses.each do |course| %>
        <%= "<div class='row course-card-row'>".html_safe if (i % 4 - 1 == 0) %>
          <div class="col-lg-3">
            <%= render "course_card", obj: course %>
          </div>
        <%= "</div><!-- close row -->".html_safe if (i % 4 == 0) %>
        <% i += 1 %>
      <% end %>
    </div>
  </div>
</div>

app/views/courses/my_courses.html.erb
<div class='container'>
  <div class='row pt-1'>
    <div class='col-md-12'>
      <% i = 1 %>
      <% @courses.each do |course| %>
        <%= "<div class='row course-card-row'>".html_safe if (i % 4 - 1 == 0) %>
          <div class="col-lg-3">
            <%= render "course_card", obj: course %>
          </div>
        <%= "</div><!-- close row -->".html_safe if (i % 4 == 0) %>
        <% i += 1 %>
      <% end %>
    </div>
  </div>
</div>

app/views/courses/new.html.erb
<div class='container'>
  <div class='row pt-3'>
    <div class='col-md-12 pt-3'>
      <%= render 'shared/errors', obj: @course %>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/courses/show.html.erb
<div class="container">
  <div class='row'>
    <div class='col-lg-12 header-row'>
      <h4>
        <%= @course.title %>
      </h4>
    </div>
  </div>
</div>
<div class="container">
  <div class="row course-show">
    <div class="col-lg-8 offset-lg-2">
      <% if has_course(current_user, @course) %>
        <!-- stations listed by station_category -->
        <% if @course.station_categories.any? %>
          <% @course.station_categories.each do |station_category| %>
            <ul class="list-group mb-3">
              <li class="list-group-item station-category-header">
                <strong><%= station_category.name %></strong>
                <span class="float-right button-group">
                  <%= link_to_if(current_user.admin?, 'Edit', edit_station_category_path(station_category), class: "btn btn-sm btn-light"){} %>
                  <%= link_to_if(current_user.admin?, 'Delete', station_category_path(station_category), method: :delete, class: "btn btn-sm btn-light" ){} %>
                </span>
              </li>
              <% if station_category.stations.any? %>
                <% station_category.stations.each do |station| %>
                  <li class="list-group-item station-header ">
                    <%= link_to station.title, station_path(station) %>
                    <span class="float-right">
                        <%= form_with(url: complete_station_path(station), method: 'put', id: "complete_toggle_#{station.id}") do |f| %>
                          <%  if current_user.completed_stations.find_by_id(station).present?
                                @checked = true
                              else
                                @checked = false
                              end
                          %>
                          <%= f.label :type, :class => "label label#{station.id}", :for => "customSwitch#{station.id}" do %>
                            <%= f.check_box(:type, :class => "label__checkbox", :id => "customSwitch#{station.id}", :onclick =>"Rails.fire(form, 'submit');", :checked => @checked ) %>
                            <span class="label__text">
                              <span class='label__check'>
                                <i class="fa fa-check icon"></i>
                              </span>
                            </span>
                          <% end %>
                        <% end %>
                      <%= link_to_if(current_user.admin?, 'Edit', edit_station_path(station), class: "btn btn-sm btn-link"){} %>
                      <%= link_to_if(current_user.admin?, 'Delete', station_path(station), method: :delete, class: "btn btn-sm btn-link" ){} %>
                    </span>
                  </li>
                <% end %>
              <% end %>
            </ul>
          <% end %>
        <% end %>
        <%= render 'admin_panel' if current_user.admin? %>
      <% else %>
        <%= render "course_description_and_signup" %>
      <%end%>
    </div>
  </div>
</div>

<script>
  $(".custom-control-input").on("click", function (){
    $("this").submit();
  });
</script>