config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#index"
  get 'my_courses', to: 'courses#my_courses'
  resources :courses, :stations, :questions, :station_categories, :payments
  resources :user_courses, only: [:create]
  authenticate :user do
    resources :courses, :except => [:show, :index]
    resources :stations, :questions, :station_categories
  end
  mount StripeEvent::Engine, at: '/stripe-event'
  resources :stations do
    put :complete, on: :member
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <span class="text-muted">&copy; 2019 STprep Ltd.</span>
    <span class="footer-link-left"><%= link_to 'Terms', '#' %></span>
    <span class="footer-link"><%= link_to 'Cookie Policy', '#' %></span>
    <span class="footer-link"><%= link_to 'Careers', '#' %></span>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id='main-nav-bar'>
  <div class='container'>
    <%= link_to root_path do %>
    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 200.7 76.7" style="enable-background:new 0 0 200.7 76.7;" xml:space="preserve" class="navbar-brand">
      <style type="text/css">
      	.st0{fill:#2274A5;}
      </style>
      <path class="st0" d="M12.8,53c-2-0.4-3.8-1.1-5.3-2.1c-0.6-0.3-1.1-0.8-1.4-1.6c-0.3-0.7-0.5-1.6-0.5-2.5c0-1.2,0.3-2.1,0.9-2.9
      	c0.6-0.8,1.4-1.1,2.4-1.1c0.7,0,1.3,0.1,1.8,0.2c0.6,0.2,1.3,0.4,2.1,0.8c1.4,0.5,2.6,0.8,3.7,1.1s2.4,0.4,4.1,0.4
      	c1.2,0,2.1-0.2,2.8-0.5c0.7-0.3,1-0.8,1-1.4c0-0.5-0.2-0.8-0.5-1.1S23,41.8,22,41.6c-0.9-0.2-2.5-0.6-4.6-1
      	c-3.9-0.7-6.7-1.9-8.4-3.4s-2.6-3.6-2.6-6.4c0-2,0.6-3.8,1.9-5.4c1.2-1.6,2.9-2.9,5.1-3.8s4.6-1.4,7.3-1.4c2,0,3.9,0.2,5.7,0.7
      	c1.8,0.5,3.5,1.2,4.9,2c1.3,0.8,2,2,2,3.8c0,1.2-0.3,2.2-1,3.1c-0.7,0.8-1.5,1.2-2.4,1.2c-1.1,0-2.5-0.4-4-1.1c-1-0.5-2-0.8-2.8-1.1
      	s-1.8-0.4-2.8-0.4c-1.1,0-1.9,0.2-2.5,0.5s-0.9,0.8-0.9,1.4c0,0.7,0.4,1.2,1.3,1.6c0.8,0.4,2.5,0.8,5.1,1.3c4.2,0.7,7.2,1.9,8.9,3.4
      	s2.6,3.7,2.6,6.5c0,3.2-1.3,5.7-4,7.6c-2.6,1.9-6.2,2.8-10.6,2.8C17.3,53.7,14.8,53.4,12.8,53z"/>
      <path class="st0" d="M62.6,49.1c0,1.5-0.6,2.7-1.8,3.4s-2.9,1-5,0.9L54,53.3c-3.9-0.3-6.9-1.5-8.9-3.6s-3-4.9-3-8.7V29.6h-1.9
      	c-3.5,0-5.2-1.4-5.2-4.3c0-2.8,1.7-4.2,5.2-4.2h1.9v-4.2c0-1.7,0.5-3,1.6-4c1-1,2.5-1.5,4.2-1.5s3.2,0.5,4.2,1.5s1.6,2.3,1.6,4V21
      	h3.6c3.5,0,5.2,1.4,5.2,4.2c0,2.9-1.7,4.3-5.2,4.3h-3.6V42c0,0.8,0.2,1.5,0.8,2.1c0.5,0.6,1.1,0.9,1.9,0.9l1.9,0.1
      	C61.2,45.4,62.6,46.7,62.6,49.1z"/>
      <path class="st0" d="M93,22.3c2.2,1.4,3.8,3.4,5,6s1.8,5.5,1.8,8.8s-0.6,6.2-1.8,8.7c-1.2,2.5-2.9,4.4-5,5.8c-2.1,1.3-4.6,2-7.4,2
      	c-2,0-3.9-0.4-5.6-1.2s-3.1-1.9-4-3.3v11.1c0,1.5-0.5,2.7-1.6,3.7c-1,0.9-2.4,1.4-4.1,1.4c-1.8,0-3.2-0.5-4.3-1.5
      	c-1.1-1-1.6-2.2-1.6-3.8V25.7c0-1.6,0.5-2.9,1.5-3.9s2.4-1.5,4.1-1.5s3,0.4,4,1.3s1.6,2,1.7,3.5c0.9-1.5,2.3-2.7,4-3.6
      	c1.8-0.9,3.7-1.3,5.8-1.3C88.4,20.2,90.9,20.9,93,22.3z M86.8,42.9c1.1-1.3,1.6-3.3,1.6-5.8c0-2.7-0.5-4.7-1.6-6.1
      	c-1.1-1.4-2.6-2.1-4.6-2.1s-3.5,0.7-4.6,2.1c-1.1,1.4-1.6,3.4-1.6,6s0.5,4.5,1.6,5.9s2.7,2.1,4.7,2.1C84.2,45,85.7,44.3,86.8,42.9z"
      	/>
      <path class="st0" d="M125.9,21.4c0.9,0.8,1.3,2,1.3,3.6c0,1.7-0.4,3-1.2,3.8c-0.8,0.8-2.3,1.3-4.3,1.5l-2,0.2
      	c-2.2,0.3-3.7,0.9-4.7,2.1c-0.9,1.1-1.4,2.6-1.4,4.5v11.2c0,1.8-0.6,3.1-1.7,4s-2.5,1.3-4.1,1.3s-3-0.4-4.1-1.3
      	c-1.1-0.9-1.7-2.2-1.7-4V25.6c0-1.7,0.6-2.9,1.7-3.9c1.1-0.9,2.4-1.4,4-1.4s2.9,0.4,3.9,1.3s1.5,2.1,1.5,3.7v1.2
      	c0.7-1.9,1.8-3.4,3.4-4.4s3.3-1.6,5-1.7l0.9-0.1C123.9,20.2,125,20.6,125.9,21.4z"/>
      <path class="st0" d="M156.6,44c0.6,0.8,0.9,1.8,0.9,3.1c0,1.7-0.8,3.1-2.5,4c-1.5,0.7-3.2,1.4-5.3,1.9c-2,0.5-3.9,0.8-5.6,0.8
      	c-3.6,0-6.7-0.7-9.3-2c-2.7-1.3-4.7-3.3-6.1-5.8c-1.4-2.5-2.2-5.5-2.2-8.9c0-3.2,0.7-6.1,2.1-8.7c1.4-2.5,3.3-4.5,5.7-5.9
      	c2.5-1.4,5.2-2.1,8.3-2.1c3,0,5.6,0.7,7.9,2c2.3,1.3,4,3.2,5.3,5.5c1.2,2.4,1.9,5.2,1.9,8.4c0,1-0.2,1.8-0.7,2.3s-1.1,0.8-2,0.8
      	h-17.2c0.3,2.1,1,3.6,2,4.5s2.6,1.4,4.6,1.4c1.1,0,2.1-0.1,3-0.4c0.9-0.2,1.9-0.6,3.1-1c0.7-0.3,1.3-0.5,1.9-0.7
      	c0.6-0.2,1.2-0.3,1.7-0.3C155.2,42.8,156,43.2,156.6,44z M139.3,29.5c-0.9,1-1.5,2.4-1.6,4.3H148c-0.3-3.8-1.9-5.7-5-5.7
      	C141.5,28.1,140.3,28.5,139.3,29.5z"/>
      <path class="st0" d="M188.6,22.3c2.2,1.4,3.8,3.4,5,6s1.8,5.5,1.8,8.8s-0.6,6.2-1.8,8.7s-2.9,4.4-5,5.8c-2.1,1.3-4.6,2-7.4,2
      	c-2,0-3.9-0.4-5.6-1.2c-1.7-0.8-3.1-1.9-4-3.3v11.1c0,1.5-0.5,2.7-1.6,3.7c-1,0.9-2.4,1.4-4.1,1.4c-1.8,0-3.2-0.5-4.3-1.5
      	S160,61.6,160,60V25.7c0-1.6,0.5-2.9,1.5-3.9s2.4-1.5,4.1-1.5c1.7,0,3,0.4,4,1.3s1.6,2,1.7,3.5c0.9-1.5,2.3-2.7,4-3.6
      	c1.8-0.9,3.7-1.3,5.8-1.3C184,20.2,186.5,20.9,188.6,22.3z M182.3,42.9c1.1-1.3,1.6-3.3,1.6-5.8c0-2.7-0.5-4.7-1.6-6.1
      	c-1.1-1.4-2.6-2.1-4.6-2.1s-3.5,0.7-4.6,2.1c-1.1,1.4-1.6,3.4-1.6,6s0.5,4.5,1.6,5.9s2.7,2.1,4.7,2.1
      	C179.7,45,181.3,44.3,182.3,42.9z"/>
    </svg>
    <% end %>

    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="#navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    	<span class="icon-bar top-bar"></span>
    	<span class="icon-bar middle-bar"></span>
    	<span class="icon-bar bottom-bar"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="navbar-nav mr-auto"></div>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item mx-2">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item mx-2">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item mx-2">
          <%= link_to "Courses", courses_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? && current_user.admin? %>
          <li class="nav-item mx-2">
            <%= link_to "Create Course", new_course_path, class: "nav-link" %>
          </li>
        <% end %>
        <% if user_signed_in? && current_user.courses.any? %>
          <li class="nav-item mx-2">
            <%= link_to_if(current_user.admin?, "All courses", my_courses_path, class: "nav-link"){} %>
            <%= link_to_if(!current_user.admin?, "My courses", my_courses_path, class: "nav-link"){} %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stprep</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column h-100">
    <%= render 'layouts/navigation'%>
    <%= render 'shared/messages' %>
      <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stprep</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <script src="https://cdn.jsdelivr.net/jquery.drawsvg/1/jquery.drawsvg.min.js"></script> -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <script>
      //TL bug fix
      document.addEventListener('DOMContentLoaded', function() {
        window.DOMLoaded = true;
      });
    </script>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="welcome-messages-container">
        <% render 'shared/messages' %>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
      document.addEventListener("turbolinks:load", function() {
        AOS.init();

        (function () {
          var s = document.createElement('script');
          s.type = 'text/javascript';
           s.async = true;
          s.src = 'https://app.termly.io/embed.min.js';
          s.id = '107e6726-a4d6-467d-9cc6-6f92a66ee9ba';
          s.setAttribute("data-name", "termly-embed-banner");
          var x = document.getElementsByTagName('script')[0];
          x.parentNode.insertBefore(s, x);
        })();
      })
    </script>
  </body>
</html>